spring.application.name=medical-system






spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=1GB

server.tomcat.max-part-count=1000
server.tomcat.max-http-form-post-size=1GB
server.tomcat.max-swallow-size=1GB





spring.datasource.url=jdbc:mysql://localhost:3306/medical_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=medical_user
spring.datasource.password=cnm1433223
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver