spring.application.name=medical-system






spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=1GB

server.tomcat.max-part-count=1000
server.tomcat.max-http-form-post-size=1GB
server.tomcat.max-swallow-size=1GB





